### PR TITLE
Expose the Latex PDF exporter

### PR DESCRIPTION
**Pull request by acspike**
I was looking to add code and prompt hiding to the Latex PDF output included with Jupyter Notebook. Your extension does this nicely, but for some reason doesn't expose the functionality. I've found that the Latex output is a bit nicer than the HTML based output for my uses. It doesn't break pages in the middle of images leaving half of the image on each page as can happen with the HTML based PDF output.

### CODE REVIEW

**Comment by kirbs-** [comment]
I'm fine with this, but we need to use a different icon so users can tell the difference.

**Comment by acspike** [comment]
Do you have a preference of icons? 

In my testing, the latex PDF export did hide code.

I've also got a commit waiting that allows hiding outputs. Which seems like a bad idea on the outset but I had a cell with undesirable outputs and streams that I couldn't silence.

**Comment by kirbs-** [comment]
> Do you have a preference of icons? 

No preference. I'm currently only using those that ship with Jupyter; Font Awesome 4.2 I think.

> In my testing, the latex PDF export did hide code.

Might be the prompt hiding that doesn't work in the latex PDF exporter. 

> I've also got a commit waiting that allows hiding outputs. Which seems like a bad idea on the outset but I had a cell with undesirable outputs and streams that I couldn't silence.

Great! I've been meaning to do this too.

**Comment by acspike** [comment]
I've changed it to the generic file-o icon.

Actually, prompt hiding seemed to work too.

**Comment by kirbs-** [comment]
I'm going to hold off merging this with the master branch until the Latex PDF exporter template is fixed. When ever Hide code is selected, the exporter hides the code and the output for the cell.

**Comment by acspike** [comment]
Would you mind if I merge the hide-ouput change set into this pull request? I know it is more proper to separate changes, but it is going to be significantly easier for me to work on the template in view of the final result, rather than trying to stage things.

**Comment by acspike** [comment]
I believe the latest revision handles this case properly.

Question: Currently code and prompts are hidden independently. Would it make sense that whenever hiding a particular code cell the associated prompt is also hidden? I'm not sure of the use case for the current behavior.

**Comment by kirbs-** [comment]
You can merge changes into one PR. Just pull down any changes from the dev branch. I've patched several bugs since the last commit on master.

My original intention was to have the hide code toolbar button toggle prompts and code together. Then provide more granular customization through the cell toolbar. However, the main toolbar button status isn't persisted in the notebook's metadata. This is another item on the to do list.

**Comment by acspike** [comment]
The current state of the branch should allow a prompt to appear without its associated code or output and vice versa. I think this more closely follows the behavior you had implemented for the HTML output.

Just to be clear, the desired behavior is that the Hide/Show Code button in the toolbar immediately hide all code and prompts (and save the status in the notebook metadata to be reflected in downloads). Clicking the button a second time shows elements again, but only elements that have not been hidden individually by a cell toolbar checkbox. Does that sound about right?

**Comment by kirbs-** [comment]
> The current state of the branch should allow a prompt to appear without its associated code or output and vice versa. I think this more closely follows the behavior you had implemented for the HTML output.

Sounds good, I'll take a look. I'd want to keep the behavior consistent between all exporters.
> Just to be clear, the desired behavior is that the Hide/Show Code button in the toolbar immediately hide all code and prompts (and save the status in the notebook metadata to be reflected in downloads). Clicking the button a second time shows elements again, but only elements that have not been hidden individually by a cell toolbar checkbox. Does that sound about right?

Correct, the button is meant as an "easy" button if a user wants to hide everything.

I'll review the updates and try to get everything documented and packaged this weekend. Thanks for contributing!

**Pull request merged**
