### PR TITLE
v0.5.5

### PR DESCRIPTION
**Pull request by kirbs-**

### CODE REVIEW

**Comment by fomightez** [comment]
I see you are planning an update soon. I was wondering if you'd be interested in adding the ability to have a `launch binder` demo that others could use to explore the extension without needing to install it somewhere first? 

I worked out what was needed [here](https://github.com/fomightez/jupyter_hide_code). You can go to that link and click the `launch binder` badge to spin up a session where it is installed. The only thing that wasn't working was the `Export to PDF via Latex` button; however, I see from this PR that it shouldn't have worked up until when this will be merged anyway.  You'll see  I haven't made a good demo page in that repository yet.

If you are interested I could wait until you make this merge and test. If everything works, then I could send you a PR. That way you'd probably just need to change the URL on the badge link after you merge. Minor points to work out:
-  I am assuming maybe your new `test.ipynb` may be a good notebook to forward to when the session spins up?
- I don't know if anything else would be need to get  the `Export to PDF via Latex` button working beyond what is in the configuration files now?

**Comment by kirbs-** [comment]
I'm not familiar with Binder, but happy to support the PR. The dev branch is ready to merge so feel free to test Binder against it. Let me know what you need from my end.

**Comment by fomightez** [comment]
If you've ever come across the `Try Jupyter` site at https://jupyter.org/try ,you've seen Binder as it is what powers those. A good example repo for Binder is [here](https://github.com/binder-examples/jupyter-extension). If you click `launch binder` there you get an active Juptyer session on demand that already has ipywidgets installed. Great for sharing developments and  training without the hassle of installing. As you can get a sense of [here](https://notebooks.gesis.org/gallery/mybinder/7d/) a lot of repositories add the ability to launch via MyBinder.

I think it would take me a bit to figure out how to test a branch of an extension via Binder, and so I'll probably just wait unless I sort it out before the latest is available via pip.

**Comment by kirbs-** [comment]
0.5.5 is available on PyPI now. I'll dig into your binder example some more. I'm planning on deprecating the bootstrapping your using. I created it before nbextensions was released. It's not a reliable way to install extensions. 

With the new version, `pip install hide_code` should be enough to install the notebook and server extensions. Not sure why it's not picked up by binder.

**Pull request merged**
